### ISSUE TITLE
Stop auto downloading games, or give option to turn it off

### ISSUE THREAD

**Issue by adamreisnz** [openfoxwq/openfoxwq_client#12]
And at any rate, please at least stop downloading games that end with "no result" (e.g. opponent leaves after 1 move). This just downloads pointless files of zero bytes onto my machine.

**Comment by jbr** [comment]
[not a contributor, nor do I know anything about dart/flutter]

I was curious about this as well and narrowed it down to [this line](https://github.com/openfoxwq/openfoxwq_client/blob/5140f4930b0824d3c0a7126207c23c8093b1521f/lib/provider/ws.dart#L519). So maybe it's just a matter of adding a boolean to [Settings](https://github.com/openfoxwq/openfoxwq_client/blob/5140f4930b0824d3c0a7126207c23c8093b1521f/lib/provider/app_settings.dart#L26C25-L26C25)?

**Comment by ale64bit** [comment]
Please note that I won't be maintaining the web openfoxwq application anymore. Join our Discord and/or take a look at  https://openfoxwq.github.io/ to know more about the change.
