### ISSUE TITLE
Feature request: Download SGF

### ISSUE THREAD

**Issue by jsepia** [openfoxwq/openfoxwq_client#3]
After I finish a game, I want to download the SGF file so I can review the game with AI.

In the desktop Fox client, this can be done by going to "Game records", opening the most recent game, and clicking on "Save".

This workflow could be optimized a bit if a "download SGF" button was shown in the UI as soon as a game is finished - if this is feasible.

**Comment by lukaszlew** [comment]
Was about to make the same feature request!
Can we get the button?

**Comment by ale64bit** [comment]
Is this about a button in the match page itself?

(just to clarify: you can currently download the SGF exactly like in the official client, by going to the game list and clicking any game. If your browser doesn't have the option to select where to download saved files enabled, you might want to check your Downloads folder)

**Comment by lukaszlew** [comment]
Yeah, the typical use case is to download the sgf directly after game and never again.
Right now you have to do 3 clicks: click the game list click refresh click the game. It is ok but I was searching for it for quite some time after commenting here.
 One click save seems natural.

**Comment by ale64bit** [comment]
I see. Yes, that makes sense, and that's what the old Qt client did (it had a "Save SGF" button in the match window) but at that point I was constructing the SGF manually.
The limitation right now is that unfortunately you need to know the ID of the game before downloading it, and for that you need to list them. I suppose that's why the official client does the same. But I can look into trying to streamline it a bit.

**Comment by lukaszlew** [comment]
Yeah, it's not that important :)

I use large desktop and low-sensitivity mouse, so it's some hassle to click refresh button:
![image](https://github.com/openfoxwq/openfoxwq_client/assets/37749/c0997ad4-f584-480a-a3a3-0ab0a5433be6)

If you feel like tuning the process, it might make sense to:
- remove the refresh button and 
- make clicking on "My Games" refresh it.

**Comment by lukaszlew** [comment]
I think this works great. 
I think we can close this one as resolved.
