### ISSUE TITLE
Could we have a linux/ubuntu app ported from this?

### ISSUE THREAD

**Issue by lmhsjackson** [openfoxwq/openfoxwq_client#5]
I usually have Debian-based distros. Is this something relatively easy to do?

**Comment by lukaszlew** [comment]
You can run webclient on any browser.

**Comment by ale64bit** [comment]
> I usually have Debian-based distros. Is this something relatively easy to do?

Yeah, I think I can give it a shot. I need to setup a VM for it. Initially I built only a Mac application because that's what people interested wanted. But there's no technical reason (that I'm aware of) to not built a Linux app as well.

**Comment by ale64bit** [comment]
Please see https://openfoxwq.github.io/.
