### ISSUE TITLE
Client is louder than other webpages.

### ISSUE THREAD

**Issue by lukaszlew** [openfoxwq/openfoxwq_client#7]
Whenever I play I have to reduce the volume because of the byo-yomi counting and stone sounds are loud.
Can we make them quieter?

**Comment by ale64bit** [comment]
Well, it should remember the volume you set the last time. You can tweak the volume of the sounds in the settings (ee screenshot below).

![Screenshot 2023-10-01 at 11 28 48](https://github.com/openfoxwq/openfoxwq_client/assets/9343380/3ce581b4-63f1-4589-a81b-4714d38de9e3)
